steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sam2-api', '.']
    id: 'build'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sam2-api']
    id: 'push'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'beta'
    - 'run'
    - 'deploy'
    - 'sam2-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/sam2-api'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--gpu'
    - '1'  # Number of GPUs
    - '--gpu-type'
    - 'nvidia-l4'  # Changed from 'nvidia-tesla-t4' to 'nvidia-l4'
    id: 'deploy'
images:
  - 'gcr.io/$PROJECT_ID/sam2-api'
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '100'
  dynamic_substitutions: true
  env:
    - 'DOCKER_BUILDKIT=1'
timeout: '3600s'