steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/gen-ai-testing-412918/your-image-name', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/gen-ai-testing-412918/your-image-name']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'your-service-name'
      - '--image'
      - 'gcr.io/gen-ai-testing-412918/your-image-name'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--cpu'
      - '1'
      - '--memory'
      - '256Mi'
      - '--max-instances'
      - '5'
      - '--timeout'
      - '300s'

images:
  - 'gcr.io/gen-ai-testing-412918/your-image-name'
